name: hirami

services:
  postgres:
    image: postgres:latest
    container_name: hirami-pg
    environment:
      POSTGRES_USER: hirami
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hirami
    ports:
      - "5432:5432"
    volumes:
      - hirami-pg:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey-bundle:latest
    container_name: hirami-valkey
    ports:
      - "6379:6379"
    volumes:
      - hirami-valkey:/data

volumes:
  hirami-pg:
  hirami-valkey:
