name: hirami

services:
  postgres:
    image: postgres:latest
    container_name: hirami-pg
    environment:
      POSTGRES_USER: hirami
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hirami
    ports:
      - "5432:5432"
    volumes:
      - hirami-pg:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey-bundle:latest
    container_name: hirami-valkey
    ports:
      - "6379:6379"
    volumes:
      - hirami-valkey:/data

  mailpit:
    image: axllent/mailpit
    container_name: hirami-mailpit
    restart: unless-stopped
    volumes:
      - hirami-mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  hirami-pg:
  hirami-valkey:
  hirami-mailpit:
